# -*- coding: utf-8 -*-
"""Final Projec DS36 Maulana - Customer Segmentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zhk6LEISPcZO_t1BAJPs0GUXQTbajvH

**Nama : Maulana\
Bootcamp : DS36\
Final Project Data Analyst : Customer Segementation (RFM) - Retail Transaction**

##1. Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""##2. Import Dataset"""

df = pd.read_csv('Retail_Transactions_Dataset.csv')

df.head()

df.info()

df['City'].nunique()

df['City'].value_counts()

"""Insight :

Data understanding
- Jumlah baris: 891,211
- Jumlah kolom: 13
- Terdapat Missing values pada Promotion: ±298K rows hilang
- Perlu convert Date ke datetime

Goals:

Berdasarkan temuan pola penurunan penjualan dan retensi pelanggan yang rendah pada periode Mei 2022 – Mei 2024, analisis ini dilakukan untuk membantu perusahaan memahami perilaku pelanggan secara menyeluruh serta merancang strategi yang dapat meningkatkan loyalitas dan pendapatan bisnis. Untuk mencapai tujuan bisnis tersebut, diperlukan serangkaian pertanyaan analisis yang dapat membantu menggali pola perilaku pelanggan, mengidentifikasi segmen bernilai tinggi, serta memahami faktor yang memengaruhi penurunan penjualan dan retensi.
sebagai berikut :

1. Bagaimana tren penjualan dan jumlah pelanggan berubah dari waktu ke waktu?
2. Segmen pelanggan mana yang paling bernilai 3. berdasarkan hasil analisis RFM?
3. Pelanggan mana yang memberikan kontribusi terbesar terhadap total pembelian?
4. Segmen pelanggan mana yang memberikan kontribusi pendapatan terbesar?
5. Bagaimana tingkat retensi pelanggan dari waktu ke waktu berdasarkan analisis cohort?

##3. Data Dictionary

| Nama Kolom             | Deskripsi                                           |
|------------------------|-----------------------------------------------------|
|Transaction_ID           | ID unik untuk setiap transaksi yang dilakukan pelanggan
|Date            | Tanggal dan waktu transaksi terjadi
|Customer_Name        | Nama pelanggan yang melakukan transaksi
|Product       | Daftar produk yang dibeli dalam satu transaksi (berbentuk list string)
|Total_Items       | Jumlah item yang dibeli dalam transaksi tersebut
|Total_Cost          | Total pengeluaran pelanggan dalam satu transaksi (USD)
|Payment_Method          | Cara pembayaran yang digunakan (Cash, Credit Card, Mobile, dll.)
|City       | Kota tempat transaksi terjadi
|Store_Type                  | Jenis toko tempat transaksi dilakukan (Department, Warehouse Club, dll.)
|Discount_Applied                 | Apakah transaksi menggunakan diskon
|Customer_Category                | Kategori pelanggan (Professional, Homemaker, dll.)
|Season               | Musim ketika transaksi terjadi (Winter, Spring, dll.)
|Promotion              | Jenis promosi yang diterapkan pada transaksi

##4. Data Cleaning
"""

# Convert Date column to datetime
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Cek hasil
df['Date'].info()

df.info()
df['Date'].head()

df["Date"].dt.year.unique()

"""Insight :

Semua transaksi sudah terformat datetime → siap untuk analisis tren penjualan per hari, bulan, kuartal, atau season.

Tidak ada missing value → tidak perlu imputasi.

Bisa digunakan untuk:

Analisis time series (tren penjualan, tren customer)

RFM Analysis di Power BI

Segmentasi berdasarkan season atau periode tertentu
"""

#cek missing value
df.isna().sum()

"""Insight:

Kolom Promotion memiliki 333.943 data kosong (~37% dari total transaksi).

Artinya, banyak transaksi tidak memiliki informasi promosi yang jelas.

Menghapus data ini akan menyebabkan kehilangan informasi besar dan potensi bias analisis.

Solusi terbaik: isi nilai kosong dengan “No Promotion” agar analisis penjualan tetap akurat dan bisa dipakai untuk dashboard & segmentasi.
"""

df['Promotion'].value_counts(dropna=False)

"""Insight :

Distribusi tiga kategori hampir merata → bagus untuk perbandingan performa tiap promo.

Banyaknya missing di promo menunjukkan kemungkinan ketidakkonsistenan input data saat transaksi.

Bisa diuji apakah transaksi tanpa promo tetap laku → peluang upsell ketika diberi promo.
"""

#Handle missing value
df['Promotion_Available'] = df['Promotion'].notna()

#si missing value di Promotion dengan “No Promotion”
df['Promotion'] = df['Promotion'].fillna("No Promotion")

#cek hasil
print(df['Promotion'].value_counts())
print(df['Promotion'].isna().sum())

"""Insight :

Kolom Promotion awalnya memiliki 333.943 missing values. Missing values tersebut diisi dengan label “No Promotion”. Selain itu, kolom baru bernama Promotion_Available ditambahkan untuk memudahkan identifikasi apakah suatu transaksi melibatkan promo atau tidak. Setelah pembersihan, tidak ada lagi nilai yang hilang pada kolom Promotion.
"""

#cek duplikat
df.duplicated().sum()

#Cek outlier kolom numerik
import matplotlib.pyplot as plt
import seaborn as sns

numerical_cols = ['Total_Items', 'Total_Cost']

for col in numerical_cols:
    plt.figure(figsize=(8,4))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot {col}')
    plt.show()

"""Insight :

Data bersih dari outlier

Insight:

Kolom waktu yang diekstrak (Year, Month, Day, Week, Day_Name, Month_Name) siap mendukung analisis tren musiman, perilaku belanja per hari, dan pola mingguan pelanggan.

# 5. Exploratory Data Analysis (EDA)

## Trend Penjualan
"""

df = pd.read_csv("Retail_Transactions_Dataset.csv")
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date')

last_full_month = (df['Date'].max().to_period('M') - 1).to_timestamp()

df_clean = df[df['Date'] <= last_full_month]

monthly_sales = df_clean.resample('ME', on='Date')['Total_Cost'].sum()
monthly_sales

plt.figure(figsize=(14,5))
plt.plot(monthly_sales.index, monthly_sales.values,
         marker='o', linestyle='-', linewidth=2)

plt.title("Tren Penjualan Bulanan")
plt.xlabel("Tahun - Bulan")
plt.ylabel("Total Penjualan")
plt.grid(True)

# Data labels dekat titik
for x, y in zip(monthly_sales.index, monthly_sales.values):
    plt.text(x, y + (y * 0.002), f"{y/1e6:.2f}M",
             ha='center', fontsize=8)

plt.tight_layout()
plt.show()

"""Insight :

Berdasarkan hasil analisis, penjualan bulanan berada pada kisaran USD 0.95M hingga 1.03M dan menunjukkan pola yang relatif stabil dari tahun 2020 hingga 2024. Meskipun terdapat beberapa penurunan kecil pada bulan-bulan tertentu, penjualan kembali naik dengan cepat, sehingga tidak terlihat gangguan signifikan pada performa bisnis. Stabilitas ini menunjukkan bahwa permintaan terhadap produk bersifat konsisten dan tidak terlalu dipengaruhi oleh kondisi musiman.

##Trend Customer Unik per Bulan
"""

monthly_customers = df_clean.resample('ME', on='Date')['Customer_Name'].nunique()
monthly_customers

plt.figure(figsize=(14,5))

plt.plot(
    monthly_customers.index,
    monthly_customers.values,
    marker='o',
    linestyle='-',
    linewidth=2,
    color='black'
)

plt.title("Tren Customer Unik per Bulan (Tanpa Bulan Tidak Lengkap)", fontsize=14)
plt.xlabel("Date")
plt.ylabel("Unique Customers")
plt.grid(True, alpha=0.3)

# Data labels (rapi, tidak terlalu jauh)
for x, y in zip(monthly_customers.index, monthly_customers.values):
    plt.text(
        x,
        y + (y * 0.002),
        str(int(y)),
        ha='center',
        fontsize=8
    )

plt.tight_layout()
plt.show()

"""Insight :

Berdasarkan hasil analisis, trend customer juga ikut terjadi pola penurunan yang sama di februari setiap tahunnya.

##Top 20 Customer Berdasarkan Spending
"""

top_customers = (
    df.groupby("Customer_Name")['Total_Cost']
    .sum()
    .sort_values(ascending=False)
    .head(20)
)

plt.figure(figsize=(14,5))
bars = top_customers.plot(kind='bar')
plt.title("Top 20 Customer by Spending")
plt.ylabel("Total Spending ($)")

# Data Labels
for bar in bars.patches:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height(),
        f'{bar.get_height():,.0f}',
        ha='center', va='bottom', fontsize=8
    )

plt.show()

"""Insight :

Analisis 20 customer dengan total belanja tertinggi menunjukkan bahwa spending terbesar berada pada kisaran USD 390 hingga 790. Tidak terdapat customer yang mendominasi secara ekstrem, sehingga kontribusi pendapatan bersifat merata. Temuan ini mengindikasikan bahwa bisnis tidak bergantung pada satu atau dua pelanggan besar, tetapi pada volume pelanggan yang banyak.

##Payment Method Distribution
"""

payment_counts = df['Payment_Method'].value_counts()

plt.figure(figsize=(10,5))
bars = payment_counts.plot(kind='bar', color='green')
plt.title("Distribusi Metode Pembayaran")
plt.ylabel("Jumlah Transaksi")

# Data Labels
for bar in bars.patches:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height(),
        f'{bar.get_height():,.0f}',
        ha='center', va='bottom', fontsize=10
    )

plt.show()

"""Insight :

Data transaksi menunjukkan bahwa metode pembayaran terdistribusi sangat merata, dengan Credit Card sedikit lebih tinggi (6.244 transaksi) di antara pilihan lainnya (Debit, Cash, dan Mobile Payment).

Meskipun metode pembayaran beragam, analisis histogram mengungkapkan bahwa mayoritas penjualan adalah dengan transaksi bernilai rendah dan bervolume tinggi, dengan kecenderungan pelanggan membeli jumlah unit yang sedikit. Secara teknis, proses StandardScaler telah berhasil meratakan skala semua fitur (Total, Unit price, dll.) ke rentang seragam, yang menjaga distribusi data asli dan memastikan data kini optimal untuk pemodelan prediktif.

##Store Type Revenue
"""

store_sales = df.groupby("Store_Type")['Total_Cost'].sum().sort_values()

plt.figure(figsize=(12,5))
bars = store_sales.plot(kind='bar', color='teal')
plt.title("Total Penjualan Berdasarkan Store Type")
plt.ylabel("Total Sales ($)")

# Data Labels
for bar in bars.patches:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height(),
        f'{bar.get_height():,.0f}',
        ha='center', va='bottom', fontsize=9
    )

plt.show()

"""Insight :

Meskipun sebagian besar tipe toko memberikan kontribusi yang stabil, yaitu di atas 210K. Namun Specialty Store yang memberikan kontribusi paling tinggi. Dan juga perlu dilakukan audit pada Convenience Store karena bernilai $7 untuk mengidentifikasi apakah itu merupakan kesalahan input data atau indikator kegagalan operasional yang parah.

##Top 15 Kota Berdasarkan Revenue
"""

city_sales = df.groupby("City")['Total_Cost'].sum().sort_values(ascending=False).head(15)

plt.figure(figsize=(14,5))
bars = city_sales.plot(kind='bar', color='purple')
plt.title("Top 15 Kota Berdasarkan Penjualan")
plt.ylabel("Total Sales ($)")

# Data Labels
for bar in bars.patches:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height(),
        f'{bar.get_height():,.0f}',
        ha='center', va='bottom', fontsize=9
    )

plt.show()

"""Insight :

Perusahaan harus memfokuskan pada optimalisasi di Specialty Store sebagai pemberi pendapatan utama dan mengalokasikan sumber daya lebih lanjut ke pasar Chicago dan Seattle. dan juga tim data harus mengaudit anomali pada tipe toko tertentu untuk memastikan integritas data seperti di type store convenience.
"""

df.to_csv("Retail_Transactions_Set.csv", index=False)

df.info()